// Code generated by protoc-gen-go.
// source: protomodel.proto
// DO NOT EDIT!

/*
Package protomodel is a generated protocol buffer package.

It is generated from these files:
	protomodel.proto

It has these top-level messages:
	Sample
*/
package protomodel

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Sample struct {
	Service      string            `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Name         string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Kind         string            `protobuf:"bytes,3,opt,name=kind" json:"kind,omitempty"`
	Label        map[string]string `protobuf:"bytes,4,rep,name=label" json:"label,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Value        float64           `protobuf:"fixed64,5,opt,name=value" json:"value,omitempty"`
	HistogramDef []string          `protobuf:"bytes,6,rep,name=histogramDef" json:"histogramDef,omitempty"`
}

func (m *Sample) Reset()         { *m = Sample{} }
func (m *Sample) String() string { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()    {}

func (m *Sample) GetLabel() map[string]string {
	if m != nil {
		return m.Label
	}
	return nil
}

func init() {
}
