apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "prometheus_aggregator-protor-{{.CurrentEnvironment}}"
  labels:
    project: prometheus_aggregator
    service: protor
    env: {{.CurrentEnvironment}}
spec:
  replicas: {{.CurrentReplica}}
  selector:
    matchLabels:
      project: prometheus_aggregator
      service: protor
      env: {{.CurrentEnvironment}}
  template:
    metadata:
      labels:
        project: prometheus_aggregator
        service: protor
        release: '{{.Version}}'
        env: {{.CurrentEnvironment}}
    spec:
      imagePullSecrets:
      - name: blregistry
      containers:
      - name: prometheus_aggregator-protor
        image: registry.bukalapak.io/bukalapak/prometheus_aggregator/protor:{{.Version}}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9090
          timeoutSeconds: 1
        ports:
        - containerPort: 9090
        command:
          - /envconsul
          - -consul=127.0.0.1:8500
          - -sanitize
          - -upcase
          - -prefix=prometheus_aggregator
          - /protor
      - name: consul
        image: registry.bukalapak.io/bukalapak/consul-image:0.0.10
        env:
        - name: SERVICE_NAME
          value: prometheus_aggregator-protor
        - name: SERVICE_ENVIRONMENT
          value: {{.CurrentEnvironment}}
        - name: SERVICE_PORT
          value: "9090"
        - name: CONSUL1
          valueFrom:
            configMapKeyRef:
              name: consul-config
              key: node1
        - name: CONSUL2
          valueFrom:
            configMapKeyRef:
              name: consul-config
              key: node2
        - name: CONSUL3
          valueFrom:
            configMapKeyRef:
              name: consul-config
              key: node3
        - name: CONSUL_ENCRYPT
          valueFrom:
            configMapKeyRef:
              name: consul-config
              key: encrypt
        ports:
        - containerPort: 8300
        - containerPort: 8301
        - containerPort: 8302
        - containerPort: 8400
        - containerPort: 8500
        - containerPort: 8600
        command: [ entrypoint, agent, -config-dir=/config, -join=$(CONSUL1), -join=$(CONSUL2), -join=$(CONSUL3), -encrypt=$(CONSUL_ENCRYPT) ]
      nodeSelector:
        env: production
